import { Student } from './types';

export const initialStudents: Student[] = [
  {
    id: 's-01',
    studentCode: 'HS00124',
    fullName: 'Nguyễn Hoàng Minh',
    dateOfBirth: '14/05/2007',
    gender: 'male',
    gradeLevel: 11,
    className: '11B1',
    parentEmail: 'hoangminh.ng@gmail.com',
    phone: '0912 345 678',
    notes: 'Hạnh kiểm Tốt, học sinh giỏi học kỳ I',
    status: 'active',
    avatarInitials: 'NM',
  },
  {
    id: 's-02',
    studentCode: 'HS00125',
    fullName: 'Trần Lê Thảo Vy',
    dateOfBirth: '22/09/2008',
    gender: 'female',
    gradeLevel: 10,
    className: '10A1',
    parentEmail: 'thaovy.tl@outlook.com',
    phone: '0988 123 456',
    notes: 'Đoàn viên thanh niên tích cực',
    status: 'active',
    avatarInitials: 'TV',
  },
  {
    id: 's-03',
    studentCode: 'HS00126',
    fullName: 'Phan Đăng Khoa',
    dateOfBirth: '03/11/2006',
    gender: 'male',
    gradeLevel: 12,
    className: '12C3',
    parentEmail: 'dangkhoa.pd@gmail.com',
    phone: '0903 555 789',
    notes: 'Tạm hoãn 1 học kỳ theo đơn gia đình',
    status: 'suspended',
    avatarInitials: 'ĐK',
  },
  {
    id: 's-04',
    studentCode: 'HS00127',
    fullName: 'Vũ Phương Linh',
    dateOfBirth: '19/01/2007',
    gender: 'female',
    gradeLevel: 11,
    className: '11B1',
    parentEmail: 'phuonglinh.vu@edu.vn',
    phone: '0977 444 333',
    notes: 'Cán sự lớp phụ trách học tập',
    status: 'active',
    avatarInitials: 'LN',
  },
  {
    id: 's-05',
    studentCode: 'HS00128',
    fullName: 'Bùi Tuấn Đức Anh',
    dateOfBirth: '08/12/2008',
    gender: 'male',
    gradeLevel: 10,
    className: '10A2',
    parentEmail: 'ducanh.bui@gmail.com',
    phone: '0914 888 999',
    notes: 'Chuyển trường theo công tác của phụ huynh',
    status: 'transferred',
    avatarInitials: 'ĐA',
  },
  {
    id: 's-06',
    studentCode: 'HS00129',
    fullName: 'Lê Thị Hồng Ngọc',
    dateOfBirth: '30/08/2007',
    gender: 'female',
    gradeLevel: 11,
    className: '11B2',
    parentEmail: 'hongngoc.le@gmail.com',
    phone: '0936 222 111',
    notes: 'Tham gia đội tuyển học sinh giỏi Văn',
    status: 'active',
    avatarInitials: 'HN',
  },
  {
    id: 's-07',
    studentCode: 'HS00130',
    fullName: 'Đỗ Hải Phong',
    dateOfBirth: '05/04/2006',
    gender: 'male',
    gradeLevel: 12,
    className: '12A3',
    parentEmail: 'haiphong.do@yahoo.com',
    phone: '0945 666 777',
    notes: 'Đội tuyển Tin học Quốc gia',
    status: 'active',
    avatarInitials: 'HP',
  },
];
